# Generated by Django 3.2.7 on 2021-09-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorvalues', '0004_auto_20210914_1019'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ass_device',
            field=models.ManyToManyField(to='sensorvalues.Devices'),
        ),
    ]
