# Generated by Django 3.2.7 on 2021-09-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210917_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_rooms',
            field=models.CharField(blank=True, max_length=50, verbose_name='Raum'),
        ),
    ]
