# Generated by Django 3.2.7 on 2021-09-16 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensorvalues', '0006_alter_deviceuserassignment_options'),
        ('profiles', '0005_remove_profile_ass_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='assigned_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensorvalues.deviceuserassignment'),
        ),
    ]
