# Generated by Django 3.2.7 on 2021-09-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorvalues', '0006_alter_deviceuserassignment_options'),
        ('profiles', '0006_profile_assigned_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='assigned_device',
        ),
        migrations.AddField(
            model_name='profile',
            name='assigned_device',
            field=models.ManyToManyField(to='sensorvalues.DeviceUserAssignment'),
        ),
    ]
