# Generated by Django 3.2.7 on 2021-09-16 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210916_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='assigned_device',
        ),
    ]
