# Generated by Django 3.2.7 on 2021-09-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('value_double', models.FloatField(blank=True, null=True)),
                ('value_integer', models.BigIntegerField(blank=True, null=True)),
                ('value_string', models.CharField(blank=True, max_length=100, null=True)),
                ('is_valid', models.BooleanField()),
            ],
            options={
                'db_table': 'data',
                'managed': False,
            },
        ),
    ]
