# Generated by Django 3.2.7 on 2021-09-16 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensorvalues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceuserassignment',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensorvalues.devices'),
        ),
    ]
