# Generated by Django 3.2.7 on 2021-09-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210917_0925'),
        ('sensorvalues', '0002_deviceuserassignment_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='assigned_to_user',
            field=models.ManyToManyField(related_name='Profile', to='profiles.Profile'),
        ),
    ]
