# Generated by Django 3.2.7 on 2021-09-19 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sensorvalues', '0003_devices_assigned_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='assigned_to_user',
            field=models.ManyToManyField(related_name='User', to=settings.AUTH_USER_MODEL),
        ),
    ]
