# Generated by Django 3.2.7 on 2021-09-14 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensorvalues', '0003_dailyaverages_mqtttreenodes_treedatapointtranslations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyaverages',
            options={'managed': False, 'verbose_name': 'Daily average', 'verbose_name_plural': 'Daily averages'},
        ),
        migrations.AlterModelOptions(
            name='data',
            options={'managed': False, 'verbose_name': 'Data row', 'verbose_name_plural': 'Data'},
        ),
        migrations.AlterModelOptions(
            name='datapoints',
            options={'managed': False, 'verbose_name': 'Datapoint', 'verbose_name_plural': 'Datapoints'},
        ),
        migrations.AlterModelOptions(
            name='devices',
            options={'managed': False, 'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelOptions(
            name='mqtttreenodes',
            options={'managed': False, 'verbose_name': 'MQTT Tree Node', 'verbose_name_plural': 'MQTT Tree Nodes'},
        ),
        migrations.AlterModelOptions(
            name='treedatapointtranslations',
            options={'managed': False, 'verbose_name': 'Tree Datapoint Translation', 'verbose_name_plural': 'Tree Datapoint Translations'},
        ),
    ]
