# Generated by Django 3.2.7 on 2021-09-16 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sensorvalues', '0004_auto_20210914_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceUserAssignment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sensorvalues.devices')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'D-U-Assignment',
                'verbose_name_plural': 'D-U-Assignments',
                'db_table': 'device_user_assignment',
            },
        ),
    ]
