# Generated by Django 3.2.7 on 2021-09-16 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensorvalues', '0005_deviceuserassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceuserassignment',
            options={'verbose_name': 'Device-User-Zuordnung', 'verbose_name_plural': 'Device-User-Zuordnungen'},
        ),
    ]
