# Generated by Django 3.2.7 on 2021-09-20 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_user_rooms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sensorvalues', '0008_devices_in_rooms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyaverages',
            options={'verbose_name': 'Tagesdurchschnitt', 'verbose_name_plural': 'Tagesdurchschnitte'},
        ),
        migrations.AlterModelOptions(
            name='datapoints',
            options={'verbose_name': 'Datenpunkt', 'verbose_name_plural': 'Datenpunkte'},
        ),
        migrations.AlterModelOptions(
            name='devices',
            options={'verbose_name': 'Gerät', 'verbose_name_plural': 'Geräte'},
        ),
        migrations.AlterModelOptions(
            name='deviceuserassignment',
            options={'verbose_name': 'Benutzer-Gerät-Zuordnung', 'verbose_name_plural': 'Benutzer-Gerät-Zuordnungen'},
        ),
        migrations.AlterModelOptions(
            name='mqtttreenodes',
            options={'verbose_name': 'MQTT-Tree-Node', 'verbose_name_plural': 'MQTT-Tree-Nodes'},
        ),
        migrations.AlterModelOptions(
            name='treedatapointtranslations',
            options={'verbose_name': 'MQTT-Tree-Datapoint-Verknüpfung', 'verbose_name_plural': 'MQTT-Tree-Datapoint-Verknüpfungen'},
        ),
        migrations.AlterField(
            model_name='devices',
            name='in_rooms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile', verbose_name='Bei Benutzer'),
        ),
        migrations.AlterField(
            model_name='deviceuserassignment',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensorvalues.devices', verbose_name='Gerät'),
        ),
        migrations.AlterField(
            model_name='deviceuserassignment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer'),
        ),
        migrations.AlterField(
            model_name='mqtttreenodes',
            name='is_leaf',
            field=models.BooleanField(verbose_name='Ist Blatt?'),
        ),
        migrations.AlterField(
            model_name='mqtttreenodes',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='mqtttreenodes',
            name='parent_id',
            field=models.BigIntegerField(verbose_name='Eltern-ID'),
        ),
        migrations.AlterField(
            model_name='treedatapointtranslations',
            name='datapoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensorvalues.datapoints', verbose_name='Datenpunkt'),
        ),
        migrations.AlterField(
            model_name='treedatapointtranslations',
            name='mqtt_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensorvalues.mqtttreenodes', verbose_name='MQTT-Node'),
        ),
    ]
