# Generated by Django 3.2.7 on 2021-09-25 07:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sensorvalues', '0010_alter_data_options'),
    ]

    operations = [

    ]
