# Generated by Django 3.2.7 on 2021-09-25 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensorvalues', '0011_alter_devices_assigned_to_user'),
    ]

    operations = [

    ]
