# Generated by Django 3.2.7 on 2021-10-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorvalues', '0015_remove_devices_assigned_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='mac_address',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='MAC-Adresse'),
        ),
    ]
