# Generated by Django 3.2.7 on 2021-10-02 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_user_rooms'),
        ('sensorvalues', '0016_alter_devices_mac_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='in_rooms',
        ),
        migrations.CreateModel(
            name='DeviceUserAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_reason', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensorvalues.devices')),
            ],
            options={
                'verbose_name': 'Benutzer-Gerät-Zuordnung',
                'verbose_name_plural': 'Benutzer-Gerät-Zuordnungen',
            },
        ),
    ]
