# Generated by Django 3.2.7 on 2021-10-06 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensorvalues', '0018_auto_20211006_0822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'get_latest_by': ['-timestamp'], 'managed': True, 'verbose_name': 'Messdaten-Eintrag', 'verbose_name_plural': 'Messdaten-Einträge'},
        ),
        migrations.AlterModelOptions(
            name='datapoints',
            options={'get_latest_by': ['-last_update'], 'verbose_name': 'Datenpunkt', 'verbose_name_plural': 'Datenpunkte'},
        ),
        migrations.AlterModelOptions(
            name='treedatapointtranslations',
            options={'verbose_name': 'MQTT-Tree-Datapoint-Verknüpfung', 'verbose_name_plural': 'MQTT-Tree-Datapoint-Verknüpfungen'},
        ),
    ]
