# Generated by Django 3.2.7 on 2021-10-24 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensorvalues', '0019_auto_20211006_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'get_latest_by': ['-timestamp'], 'managed': True, 'verbose_name': 'Messwert', 'verbose_name_plural': 'Messwerte'},
        ),
    ]
