# Generated by Django 3.2.7 on 2021-09-20 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usernotifications', '0002_message_incident_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='incident_data',
            new_name='incident_date',
        ),
    ]
