# Generated by Django 3.2.7 on 2021-09-20 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usernotifications', '0003_rename_incident_data_message_incident_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='incident_date',
        ),
    ]
