# Generated by Django 3.2.7 on 2021-09-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usernotifications', '0004_remove_message_incident_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Benutzermeldung', 'verbose_name_plural': 'Benutzermeldungen'},
        ),
        migrations.AddField(
            model_name='message',
            name='incident_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Vorfalldatum'),
        ),
    ]
