# Generated by Django 3.2.7 on 2021-09-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usernotifications', '0005_auto_20210920_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gelesen'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gesendet'),
        ),
    ]
