# Generated by Django 3.2.7 on 2021-09-22 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usernotifications', '0006_auto_20210920_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
