# Generated by Django 3.2.7 on 2021-09-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usernotifications', '0007_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Benutzermeldung', 'verbose_name_plural': 'Benutzermeldungen'},
        ),
    ]
