# Generated by Django 3.2.7 on 2021-10-13 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensorvalues', '0019_auto_20211006_0827'),
        ('usernotifications', '0010_alter_message_user_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user_devices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensorvalues.deviceuserassignment', verbose_name='Betroffene Geräte'),
        ),
    ]
