# Generated by Django 3.2.7 on 2021-09-20 10:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blogeintrag', 'verbose_name_plural': 'Blogeinträge'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(limit_value=50, message='Der Bloginhalt sollte mindestens 50 Zeichen enthalten!')], verbose_name='Inhalt'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Veröffentlichungsdatum'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Titel'),
        ),
    ]
